apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-deployment
  labels:
    app: person
spec:
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
      - name: person
        image: person:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://db:5434/person"
      - name: auftrag
        image: auftrag:local
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://db:5433/auftrag"
      - name: shop
        image: shop:local
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
