apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
  labels:
    app: person
spec:
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
      - name: person
        image: person:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://192.168.64.9:5434/person"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "http://192.168.64.9:8080/auth"
