apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
spec:
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: shop:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "http://192.168.64.9:8080/auth"
